name: Build and Deploy Documentation

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyQt5
        run: pip install PyQt5 PyQt5-stubs
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pdoc
        run: pip install pdoc

      - name: Build documentation
        run: |
          mkdir -p docs
          pdoc src -o docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs


  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
